#this is a quiz game woohoo
print("PLEASE READ ALL THE LINES DO NOT MISS A SINGLE LINE")
print("Hello , Hi , HOWDY!!! welcome to my quiz game  ")
print("there are a total 6 questions ")
print("lets see how much you will get")
print("also please keep a track of your score cause you are going to get a report card at the end")

person= input("{type 'yes' or 'no' and press 'q' to quit} Do you want to play? =")

if person=='yes':
    print("good lets start with the questions")
elif person =='no':
    print("okay nerd goodbye!")
    quit()
elif person=='q':
    quit()
else:
    print("okay i think that is a no so CYAAAAA")
    quit()

answer1= input("Question 1: what does ISS stand for  ")
if answer1==("international space station"):
    print("Correct means you are a nerd in a good way!")
else:
    print("bhaisap you have to get good")

print("Great start :D, lets move on")

print(" Question 2: what is the right method of doing Chest Compressions" )
print("option !: 100-120 bpm")
print("option @: 80-90 bpm")
print("option #: 50-60 bpm")
print("option $: 0 bpm marne doo salee ko")
answer2= input("So what is your answer {type any of the following (!,@,# or $)} = ")
if answer2=="!":
    print("yay you got it right! keep it up you may save a person one day")
elif answer2!="!":
    print("brother/behan please get good this is GK GKKKK you are wrong")

print("lets move on")

answer3=input("Question 3: Do you know the basics of coding? ")
if answer3=='yes':
    print("Great!")
    print("Now i am going to ask questions regarding coding ready or not ")
elif answer3!='yes':
    print("dude no how dont you know AHHHHHH but i will still give you these questions so TRY OKAY")

answerc1=input("Question 1 in coding: what is the command given for printing something? ")
if answerc1=='print':
    print("great you are doing good ")
else:
    print("dude WOW! you have get good")

print("fine lets move on to the next question okay ")
print("Question 2 in coding: what is the command for entering any string ex:i,q,,,!,#,F, anything")
print("but not numbers what is the command")
print("Option 1: q=int(input() / q=float(input()")
print("Option 2: q = input() / q = str(input()")
answerc2=input("So what is your option (Type either 1 or 2) = ")
if answerc2=="2":
    print("GREAT you are doing awesome WOHO")
else:
    print("I am really REALLY disappointed by you HUH!")

print(" Question 3 in coding: what is the full form of ICT" )
print("option a: information communication telepath")
print("option b: i cant think")
print("option c: imfultrate came to talk")
print("option d: information communication technology")
answerc3= input("So what is your answer {type any of the following (a,b,c or d)} = ")
if answerc3=="d":
    print("Tok Nice (inspired by a meme")
elif answerc3!="d":
    print("well you have to get a life this is wronngggggg gosh")

print("ok we are done with coding questions and one gk")

print("I Think that is it, I will give you a report card now")

#this is a percentage generater

print("hello this is your report card so fill the information correctly")
Name=input("Enter the name of the player = ")
q=float(input("{question is for 1 mark} score of the First question = "))
if q=="1":
    print("Good Job!")
elif q=="0":
    print("Worthless meetsack")
w=float(input("{question is for 1 mark} score of the Second question = "))
if w=="1":
    print("Good Job!")
elif w=="0":
    print("Worthless meetsack")
e=float(input("{question is for 1 mark} score of the Third question = "))
if e=="1":
    print("Good Job!")
elif e=="0":
    print("Worthless meetsack")
r=float(input("{question is for 1 mark} score of the Fourth question = "))
if r=="1":
    print("Good Job!")
elif r=="0":
    print("Worthless meetsack")
t=float(input("{question is for 1 mark} score of the Fifth question = "))
if t=="1":
    print("Good Job!")
elif t=="0":
    print("Wortless meetsack")
y=float(input("s{question is for 1 mark} core of the Sixth question = "))
if y=="1":
    print("Good Job!")
elif y=="0":
    print("Worthless meetsack")
total= q+w+e+r+t+y
p=(total/6)*100
print("\t\t\t this is a  coded percentage generated by THE LEGEND")
print("\t\t\t this is the percentage card!!!")
print("Name of the player is = ", Name)
print("this human got this much in First question =", q)
print("this human got this much in Second question =", w)
print("this human got this much in Third question =", e)
print("this human got this much in Forth question =", r)
print("this human got this much in Fifth question =", t)
print("this human got this mcuh in Sixth question =", y)
print("\t\t\t\t this human got this much in total = ", total )
print("\t\t\t\t and for the movement you all been waiting for PERCENTAGE! = ", p)
if p<50:
    print("this is a text i left on the night of 15/07/2022 while coding in a bus (you are useless and you will fail in life)")
elif p>80:
    print("this is a text i left on the night of 15/07/2022 while coding in a bus (you are awesome you did a good job) ")

print("HEY I AM SORRY IF YOU HAVE DONE BAD AND FOR PEOPLE WHO DID GOOD I CONGO YOU :)")
print("hey before you go I want to tell you something ")
ihopeheorshewillpressthis= input("type (yes) if you want to hear it or (no) if you done want to hear it = ")

if ihopeheorshewillpressthis=='yes':
    print(" this is the coders last words")
    print("Never gonna give you up")
    print("ever gonna let you down")
    print("Never gonna run around and desert you")
    print("Never gonna make you cry")
    print("Never gonna say goodbye")
    print("Never gonna tell a lie and hurt you")
    print("HAHA GOT YOU CYAAAAAA")
    quit()

if ihopeheorshewillpressthis!='yes':
    print("please this took me 18 hours to code")
    print(" this is the coders last words")
    print("Never gonna give you up")
    print("Never gonna let you down")
    print("Never gonna run around and desert you")
    print("Never gonna make you cry")
    print("Never gonna say goodbye")
    print("Never gonna tell a lie and hurt you")
    print("HAHA GOT YOU CYAAAAAA")
    quit()